language: php

php:
  - 7.3
  - 7.2
  - 7.1

before_install:
  - pecl install xdebug
  - phpenv rehash

before_script:
  - composer selfupdate

script:
  - ant composer-init
  - ant build

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/clover.xml
